# Generated by Django 3.1.2 on 2021-07-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alsstatus',
            name='time_stamp',
            field=models.DateTimeField(null=True),
        ),
    ]
