# Generated by Django 4.1.7 on 2023-07-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supbrocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField(default=None, unique=True)),
                ('name', models.CharField(default=None, editable=False, max_length=50)),
            ],
        ),
    ]
