# Generated by Django 3.1.2 on 2021-07-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0002_auto_20210705_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='alsstatus',
            name='device_name',
            field=models.CharField(default='D735', max_length=4),
        ),
    ]
