# Generated by Django 4.1.7 on 2023-07-10 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0003_supbrocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionKeyLEDBoolRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid MAC address', regex='^[0-9a-fA-F]{12}$')], verbose_name='MAC address')),
                ('ip_address', models.GenericIPAddressField()),
                ('phone_model', models.CharField(choices=[('D335', 'D335'), ('D385', 'D385'), ('D713', 'D713'), ('D717', 'D717'), ('D735', 'D735'), ('D785', 'D785'), ('D862', 'D862'), ('D865', 'D865')], max_length=4, null=True)),
                ('write_groupaddress', models.CharField(max_length=8, null=True)),
                ('status_groupaddress', models.CharField(max_length=8, null=True)),
                ('led_number', models.PositiveSmallIntegerField(null=True)),
                ('led_color_for_on', models.CharField(choices=[('---', '---'), ('green', 'green'), ('red', 'red'), ('orange', 'orange')], max_length=8, null=True)),
                ('led_color_for_off', models.CharField(choices=[('---', '---'), ('green', 'green'), ('red', 'red'), ('orange', 'orange')], default='---', max_length=8, null=True)),
                ('phone_location', models.CharField(default=None, max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FunctionKeyLEDSubscriptions',
        ),
    ]
