# Generated by Django 3.1.2 on 2021-07-05 20:19

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0004_auto_20210705_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alsstatus',
            name='time_stamp',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now(), null=True),
        ),
    ]
