# Generated by Django 3.1.2 on 2021-07-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0008_auto_20210705_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alsstatus',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
