# Generated by Django 3.0.8 on 2021-08-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0011_knxstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnxStatus',
            new_name='KnxMonitor',
        ),
    ]
