# Generated by Django 3.0.8 on 2021-09-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0013_knxstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='knxmonitor',
            name='raw_frame',
            field=models.CharField(default=0, max_length=16384),
        ),
    ]
