# Generated by Django 3.0.8 on 2021-09-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0014_knxmonitor_raw_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knxmonitor',
            name='raw_frame',
            field=models.BinaryField(default=0, max_length=16384),
        ),
    ]
