# Generated by Django 3.0.8 on 2021-09-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0015_auto_20210913_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knxmonitor',
            name='raw_frame',
            field=models.CharField(default=0, max_length=16384),
        ),
    ]
