# Generated by Django 3.2.7 on 2021-09-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0016_auto_20210913_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knxmonitor',
            name='groupaddress',
            field=models.JSONField(),
        ),
    ]
