# Generated by Django 3.2.7 on 2021-09-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0017_alter_knxmonitor_groupaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knxmonitor',
            name='groupaddress',
            field=models.CharField(max_length=9),
        ),
    ]
