# Generated by Django 4.1.4 on 2022-12-25 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0017_alter_alsstatus_id_alter_brightnessrules_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(editable=False, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid MAC address', regex='^[0-9a-fA-F]{12}$')], verbose_name='MAC address')),
                ('ip_address', models.GenericIPAddressField()),
                ('manufacturer', models.CharField(choices=[('Snom', 'Snom')], default='Snom', max_length=20)),
                ('type', models.CharField(choices=[('D735', 'D735')], default='D735', max_length=4)),
                ('label', models.CharField(default=None, max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groupaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maingroup', models.CharField(default=None, editable=False, max_length=50)),
                ('subgroup', models.CharField(default=None, editable=False, max_length=50)),
                ('address', models.CharField(default=None, editable=False, max_length=9)),
                ('address_name', models.CharField(default=None, editable=False, max_length=50)),
                ('datapoint_type', models.CharField(default=None, editable=False, max_length=50)),
                ('html_action', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
