# Generated by Django 4.1.4 on 2022-12-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0018_device_groupaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupaddress',
            old_name='address_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='groupaddress',
            name='alias',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
