# Generated by Django 4.1.7 on 2023-03-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knx", "0019_rename_address_name_groupaddress_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupaddress",
            name="code",
            field=models.CharField(default=None, max_length=4),
        ),
    ]
