# Generated by Django 4.1.7 on 2023-03-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knx", "0021_alter_groupaddress_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupaddress",
            name="code",
            field=models.CharField(max_length=4),
        ),
    ]
