# Generated by Django 4.1.7 on 2023-03-02 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("knx", "0022_alter_groupaddress_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupaddress",
            name="code",
        ),
    ]
