# Generated by Django 4.1.7 on 2023-03-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knx", "0023_remove_groupaddress_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupaddress",
            name="code",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
