# Generated by Django 3.0.8 on 2023-03-06 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0024_groupaddress_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionKeyLEDSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid MAC address', regex='^[0-9a-fA-F]{12}$')], verbose_name='MAC address')),
                ('ip_address', models.GenericIPAddressField()),
                ('type', models.CharField(choices=[('D713', 'D713'), ('D785', 'D785')], default='D785', max_length=4)),
                ('led_number_for_on', models.CharField(default=None, max_length=2)),
                ('led_number_for_off', models.CharField(default=None, max_length=2)),
                ('knx_subscription', models.CharField(default=None, max_length=8)),
                ('on_subscription_change_url', models.URLField(blank=True, default=None)),
                ('fkey_no', models.CharField(blank=True, default=None, max_length=2)),
                ('phone_location', models.CharField(default=None, max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='alsstatus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brightnessrules',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupaddress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='knxmonitor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='knxstatus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
