# Generated by Django 3.2.18 on 2023-03-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0025_auto_20230306_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionkeyledsubscriptions',
            name='type',
        ),
        migrations.AddField(
            model_name='functionkeyledsubscriptions',
            name='phone_model',
            field=models.CharField(choices=[('D335', 'D335'), ('D385', 'D385'), ('D713', 'D713'), ('D717', 'D717'), ('D735', 'D735'), ('D785', 'D785'), ('D865', 'D865')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='alsstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brightnessrules',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='functionkeyledsubscriptions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='functionkeyledsubscriptions',
            name='knx_subscription',
            field=models.CharField(choices=[('1/0/0', '1/0/0'), ('1/0/1', '1/0/1'), ('1/0/5', '1/0/5'), ('1/0/6', '1/0/6'), ('1/0/10', '1/0/10'), ('1/0/15', '1/0/15'), ('1/1/0', '1/1/0'), ('1/1/5', '1/1/5'), ('1/2/10', '1/2/10'), ('1/2/11', '1/2/11'), ('1/2/12', '1/2/12'), ('1/2/13', '1/2/13'), ('1/2/20', '1/2/20'), ('1/2/21', '1/2/21'), ('1/2/22', '1/2/22'), ('1/2/23', '1/2/23'), ('1/2/30', '1/2/30'), ('1/2/31', '1/2/31'), ('1/2/32', '1/2/32'), ('1/2/40', '1/2/40'), ('1/2/45', '1/2/45'), ('1/7/10', '1/7/10'), ('2/0/0', '2/0/0'), ('2/0/1', '2/0/1'), ('2/0/2', '2/0/2'), ('2/0/3', '2/0/3'), ('2/0/4', '2/0/4'), ('2/0/5', '2/0/5'), ('3/0/0', '3/0/0'), ('4/7/10', '4/7/10')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='functionkeyledsubscriptions',
            name='led_number_for_off',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='functionkeyledsubscriptions',
            name='led_number_for_on',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='groupaddress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='knxmonitor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='knxstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
